
---

- name: install taps of homebrew
  homebrew_tap: tap="{{ item }}" state=present
  with_items: "{{ homebrew_taps }}"
  tags:
    - brew

- name: update homebrew
  homebrew: update_homebrew=yes
  tags:
    - brew

- name: install homebrew packages
  homebrew: name="{{ item.name }}" state="{{ item.state|default('latest') }}" install_options="{{ item.install_options|default() }}"
  with_items: "{{ homebrew_packages }}"
  tags:
    - brew

- name: install homebrew cask packages
  homebrew_cask: name="{{ item }}" state=present
  with_items: "{{ homebrew_cask_packages }}"
  ignore_errors: true
  tags:
    - cask

